### ISSUE TITLE
Error report while using your program

### ISSUE THREAD

**Issue by majid-derkaoui** [optiv/Freeze.rs#1]
Hello,

I wanted to inform you that I encountered some issues while using your program. The following errors were detected: E0405, E0412, E0432, E0433, E0463.

I found that these errors come with detailed explanations and that more information can be obtained by using the command rustc --explain E0405.

When attempting to compile typenum using the cargo build command, it was reported that there were 150 previous errors, and the command ultimately failed.

I hope you can assist me in resolving this issue. Thank you in advance for your efforts.

Best regards,

**Comment by Tylous** [comment]
Hello, I will need more context, I don't know if this is occurring when you compile freeze.rs or make a payload with it. Please provide me the commands you ran, and any output or screenshots to help me troubleshoot this better.

**Comment by majid-derkaoui** [comment]
Okay, thank you. I will provide you with more information about the commands I ran and their results, and I will also attach some pictures if possible. Thank you for helping me troubleshoot this issue more effectively.

**Comment by RedHeadSec** [comment]
@majid-derkaoui Once compiled, move the new Freeze binary out of the release folder, to either the main root folder of the project or a tools folder w/e. Delete any old Cargo.toml or project folders for the payload you attempted to create and it should resolve this. 
Example: 
![Parrot_OS](https://user-images.githubusercontent.com/42355245/236223214-60630b82-7c59-4c8b-8beb-e19807a6db0f.png)

Move to root of project at /opt/Freeze.rs

![Parrot_OS](https://user-images.githubusercontent.com/42355245/236223922-6dfabe00-f812-42f8-b179-be1c36918a15.png)

Profit:
![Parrot_OS](https://user-images.githubusercontent.com/42355245/236224381-ce79fea9-30c6-445d-a3e1-726d3d6a1b94.png)

**Comment by majid-derkaoui** [comment]
Hello Optiv,

I hope this message finds you well. I wanted to inform you that I have taken some screenshots of the terminal which illustrate the issue we discussed earlier. I believe these screenshots will be helpful for you to better understand the problem and assist me in resolving it.

Please let me know if there is any other information I can provide to help troubleshoot this issue. Thank you for your assistance.

Best regards,

![Screenshot_2023-05-04_21_36_23](https://user-images.githubusercontent.com/54225189/236324943-89e5a68c-2282-489b-a372-75b11a210367.png)
![Screenshot_2023-05-04_21_36_29](https://user-images.githubusercontent.com/54225189/236325017-6586fdaf-9111-48ca-b649-240aa56ec9db.png)
![Screenshot_2023-05-04_21_36_53](https://user-images.githubusercontent.com/54225189/236325043-d65c5eca-5276-45a4-8931-3115f053d740.png)

**Comment by majid-derkaoui** [comment]
> 

Hello RedHeadSec,
Thank you for your invaluable assistance and suggestions in resolving the issue I was facing. I will be trying out the suggestions you provided and will let you know if I require any further assistance.

Thank you for your professionalism and dedication to providing excellent service.

Best regards,

**Comment by majid-derkaoui** [comment]
Dear RedHeadSec,

The solution you proposed did not work for me and the problem still persists. Could you please provide me with further suggestions or advice to help me resolve this issue?

Thank you for your support.

**Comment by Tylous** [comment]
@majid-derkaoui  Do you have all the proper rust dependencies installed? If so please let them all for me so I can replicate it on my end.

**Comment by majid-derkaoui** [comment]
@Tylous I have reinstalled Rust dependencies again, and the results were great,I would like to express my deep gratitude to you, Mr. Tylous, for the help and attention you provided me.

Thank you for your support.

**Comment by Tylous** [comment]
No problem happy to help.
